name: 'Setup'
description: 'Perform various shared setup tasks'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: '16.x'
outputs:
  changed-files:
    description: "List of files changed in this PR, in JSON format"
    value: ${{ steps.changed.outputs.added_modified }}
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}${{ inputs.node-version }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}${{ inputs.node-version }}-node-modules-
    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Fetch the base ref
      shell: bash
      run: |
        # Make sure we also fetch the base ref so that ESLint, Flow, and Jest
        # have a ref to compare against.
        git fetch --depth 1 origin ${GITHUB_BASE_REF}
    - name: Get All Changed Files
      uses: jaredly/get-changed-files@absolute
      id: changed
      with:
        format: 'json'