name: 'Filter files'
description: 'Filter the list of changed files'
inputs:
  changed-files:
    description: 'Space-separated list of changed files from setup'
    required: true
  files:
    description: 'comma-separated list of files to check for'
    required: false
  extensions:
    description: 'comma-separated list of extensions to check for'
    required: false
outputs:
  filtered:
    description: 'The list of files that match'
    value: ${{ steps.result.outputs.result }}
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: result
      with:
        script: |
          // const extensionsRaw = "${{ inputs.extensions }}";
          // const exactFilesRaw = "${{ inputs.files }}";
          // const inputFiles = "${{ inputs.changed-files }}".split(' ').filter(Boolean);
          const extensionsRaw = context.inputs.extensions;
          const extensions = extensionsRaw.trim() ? extensionsRaw.split(',') : [];
          const exactFilesRaw = context.inputs.files;
          const exactFiles = exactFilesRaw.trim() ? exactFilesRaw.split(',') : [];
          const inputFiles = context.inputs['changed-files'].split(' ').filter(Boolean);
          
          return inputFiles.filter(name => {
            return extensions.some(ext => name.endsWith(ext)) || (
              exactFiles.includes(name)
            )
          }).join(' ');
        result-encoding: string